### ISSUE TITLE
Mind is broken

### ISSUE THREAD

**Issue by ghost** [shinh/ags#11]
your output:
```
M-code file not exist(test.mco)\n
```

stderr: (none)

Seems to occur so whatever I try to run.

**Comment by shinh** [comment]
It seems I can create a valid solution for a simple problem:

http://golf.shinh.org/reveal.rb?Helloworld/shinh_1630272065&mind

**Comment by ghost** [comment]
Thank you for checking.

I've just tried with this on performance checker:

```
メインは
3と
4を
加え
結果を
表示
```

I got an error that `M-code file not exist` when I ran it, but removing the line `結果を` produced successful exit status; I guess invalid syntax generates such the error rather than compile error (I am not familiar with the language at all).
